
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "fastapi-app"
    static_configs:
      - targets: ["api:8000"] # "api" is the name of your service in docker-compose

  - job_name: "cadvisor"
    static_configs:
      - targets: ['cadvisor:8080'] # Inside the docker network, it's still 8080

  - job_name: "qdrant"
    static_configs:
        - targets: ['qdrant:6333'] # Inside the docker network, it's still 6333
  - job_name: "redis"
    static_configs:
        - targets: ['redis:6379'] # Inside the docker network, it's still 9121